import { PrismaClient } from '@prisma/client';

const db = new PrismaClient();

async function seed() {
  const products = [
    {
      brand: "Hikvision",
      modelName: "DS-2CD2143G2-IU",
      cameraType: "Dome",
      resolution: "4MP",
      technology: "IP",
      recorderType: "NVR",
      nightVision: "Up to 30m EXIR 2.0",
      weatherRating: "IP67",
      price: 4500,
      salePrice: 3899,
      description: "Hikvision 4MP WDR Dome Network Camera with built-in mic and SD card slot. Ideal for indoor and outdoor surveillance with excellent low-light performance.",
      features: "4MP Resolution,Built-in Microphone,SD Card Slot (up to 256GB),WDR 120dB,IP67 Weatherproof,PoE Powered,H.265+ Compression,Mobile App Support",
      imageUrl: "",
      irRange: "30m",
      fieldOfView: "106° Diagonal",
    },
    {
      brand: "Hikvision",
      modelName: "DS-2CD2T47G2-L",
      cameraType: "Bullet",
      resolution: "4MP",
      technology: "IP",
      recorderType: "NVR",
      nightVision: "Up to 40m EXIR 2.0",
      weatherRating: "IP67",
      price: 5200,
      salePrice: 4499,
      description: "Hikvision 4MP Bullet Network Camera with ColorVu technology for full-color night vision. Features powerful IR range and smart analytics.",
      features: "4MP Resolution,ColorVu Technology,40m IR Range,IP67 Weatherproof,Powered by PoE,H.265+ Compression,Smart Motion Detection,Audio Alarm",
      imageUrl: "",
      irRange: "40m",
      fieldOfView: "87° Diagonal",
    },
    {
      brand: "Dahua",
      modelName: "IPC-HDW2231T-AS",
      cameraType: "Dome",
      resolution: "2MP",
      technology: "IP",
      recorderType: "NVR",
      nightVision: "Up to 30m IR",
      weatherRating: "IP67",
      price: 3200,
      salePrice: 2799,
      description: "Dahua 2MP WDR Dome Camera with Starlight technology for clear images in near-darkness. Compact design suits offices and retail spaces.",
      features: "2MP Starlight Sensor,WDR 120dB,Built-in Mic,SD Card Slot,IP67 Rated,H.265+ Compression,Smart IR,Onvif Compliant",
      imageUrl: "",
      irRange: "30m",
      fieldOfView: "103° Diagonal",
    },
    {
      brand: "Dahua",
      modelName: "IPC-HFW2431E-S-S2",
      cameraType: "Bullet",
      resolution: "4MP",
      technology: "IP",
      recorderType: "NVR",
      nightVision: "Up to 50m IR",
      weatherRating: "IP67",
      price: 5800,
      salePrice: 4999,
      description: "Dahua 4MP WDR Bullet Camera with SMD 3.0 analytics and excellent night vision. Built for perimeter security and long-range monitoring.",
      features: "4MP Resolution,SMD 3.0 Analytics,50m Smart IR,WDR 140dB,IP67 Weatherproof,PoE Powered,H.265+ Compression,Face Detection",
      imageUrl: "",
      irRange: "50m",
      fieldOfView: "83° Diagonal",
    },
    {
      brand: "Ezviz",
      modelName: "C6N Smart WiFi Camera",
      cameraType: "WiFi",
      resolution: "2MP",
      technology: "WiFi",
      recorderType: "Cloud/SD",
      nightVision: "Up to 10m",
      weatherRating: "Indoor",
      price: 2499,
      salePrice: 1999,
      description: "Ezviz C6N 2MP Smart WiFi Pan/Tilt Camera for indoor use. 360° coverage with smart tracking, two-way audio, and night vision. No NVR needed.",
      features: "2MP 1080p,360° Pan/Tilt,Smart Motion Tracking,Two-Way Audio,Night Vision up to 10m,WiFi Connectivity,SD Card Slot,App Control",
      imageUrl: "",
      irRange: "10m",
      fieldOfView: "360° Horizontal",
    },
    {
      brand: "Ezviz",
      modelName: "C8C Outdoor WiFi Camera",
      cameraType: "WiFi",
      resolution: "2MP",
      technology: "WiFi",
      recorderType: "Cloud/SD",
      nightVision: "Up to 30m",
      weatherRating: "IP66",
      price: 3999,
      salePrice: 3499,
      description: "Ezviz C8C 2MP Outdoor WiFi Bullet Camera with active deterrence. Features built-in siren and strobe light to warn off intruders. IP66 rated.",
      features: "2MP 1080p,Active Deterrence (Siren+Strobe),IP66 Weatherproof,30m Night Vision,WiFi,SD Card Slot,Two-Way Audio,Smart Alerts",
      imageUrl: "",
      irRange: "30m",
      fieldOfView: "110° Diagonal",
    },
    {
      brand: "CP Plus",
      modelName: "CPL-C3-VC2218L",
      cameraType: "Dome",
      resolution: "2MP",
      technology: "Analog",
      recorderType: "DVR",
      nightVision: "Up to 20m IR",
      weatherRating: "IP66",
      price: 1599,
      salePrice: 1299,
      description: "CP Plus 2MP HD Analog Dome Camera with IR night vision and weatherproof housing. Budget-friendly option for basic home and shop surveillance.",
      features: "2MP HD Resolution,20m IR Night Vision,IP66 Weatherproof,OSD Menu,Auto White Balance,Low Light Compensation,Wide Dynamic Range",
      imageUrl: "",
      irRange: "20m",
      fieldOfView: "85° Diagonal",
    },
    {
      brand: "CP Plus",
      modelName: "CP-X-ADC-V8121L",
      cameraType: "Bullet",
      resolution: "2MP",
      technology: "Analog",
      recorderType: "DVR",
      nightVision: "Up to 25m IR",
      weatherRating: "IP66",
      price: 1799,
      salePrice: 1499,
      description: "CP Plus 2MP HD Analog Bullet Camera with powerful IR night vision. Easy to install and compatible with all CP Plus DVRs.",
      features: "2MP HD Resolution,25m IR Night Vision,IP66 Weatherproof,Metal Housing,High Definition Output,3D DNR,Smart IR",
      imageUrl: "",
      irRange: "25m",
      fieldOfView: "78° Diagonal",
    },
    {
      brand: "Hikvision",
      modelName: "DS-2DE4A425IWG-E",
      cameraType: "PTZ",
      resolution: "4MP",
      technology: "IP",
      recorderType: "NVR",
      nightVision: "Up to 150m IR",
      weatherRating: "IP67",
      price: 35000,
      salePrice: 29999,
      description: "Hikvision 4MP 25x PTZ Network Camera with IR up to 150m. Ideal for large outdoor areas, parking lots, and perimeter surveillance with auto-tracking.",
      features: "4MP Resolution,25x Optical Zoom,150m Smart IR,Auto-Tracking,IP67 Weatherproof,PoE+,H.265+,Smart Analytics,Pre-set Tours",
      imageUrl: "",
      irRange: "150m",
      fieldOfView: "58.4° - 6.2° (varies with zoom)",
    },
    {
      brand: "Dahua",
      modelName: "IPC-HFW3841E-AS-PV",
      cameraType: "Bullet",
      resolution: "8MP",
      technology: "IP",
      recorderType: "NVR",
      nightVision: "Up to 50m IR",
      weatherRating: "IP67",
      price: 12000,
      salePrice: 9999,
      description: "Dahua 8MP (4K) Ultra HD Bullet Camera with TiOC active deterrence. Built-in siren and strobe for perimeter protection with AI analytics.",
      features: "8MP 4K Resolution,TiOC Active Deterrence,SMD Plus Analytics,50m Smart IR,WDR 140dB,IP67,H.265+,Face Detection,Perimeter Protection",
      imageUrl: "",
      irRange: "50m",
      fieldOfView: "98° Diagonal",
    },
    {
      brand: "Hikvision",
      modelName: "DS-7204HUHI-K1",
      cameraType: "DVR",
      resolution: "4MP",
      technology: "Analog",
      recorderType: "DVR",
      nightVision: "N/A",
      weatherRating: "N/A",
      price: 6999,
      salePrice: 5999,
      description: "Hikvision 4-ch 4MP DVR with 1 HDD bay. Supports both analog and IP cameras. Ideal for small homes and shops requiring reliable recording.",
      features: "4 Channels,4MP Recording,1 HDD Bay (up to 10TB),H.265+ Compression,4-in-1 Camera Support,P2P Remote View,Smart Search,Mobile App",
      imageUrl: "",
      irRange: "N/A",
      fieldOfView: "N/A",
    },
    {
      brand: "Hikvision",
      modelName: "DS-7604NI-K2-4P",
      cameraType: "NVR",
      resolution: "8MP",
      technology: "IP",
      recorderType: "NVR",
      nightVision: "N/A",
      weatherRating: "N/A",
      price: 8999,
      salePrice: 7999,
      description: "Hikvision 4-ch 8MP NVR with 4 PoE ports. Plug-and-play setup with Hikvision IP cameras. Supports up to 6TB HDD for weeks of recording.",
      features: "4 Channels,8MP Recording,4 PoE Ports,1 HDD Bay (up to 6TB),H.265+,Plug & Play,P2P Remote View,Smart Search,VCA Analytics",
      imageUrl: "",
      irRange: "N/A",
      fieldOfView: "N/A",
    },
  ];

  console.log("Seeding products...");
  for (const p of products) {
    await db.cctvProduct.create({ data: p });
    console.log(`  Created: ${p.brand} ${p.modelName}`);
  }
  console.log(`Done! Seeded ${products.length} products.`);
}

seed()
  .catch(console.error)
  .finally(() => db.$disconnect());